application: ppdb-smk5palembang
version: 2
runtime: php
api_version: 1
threadsafe: false

handlers:
  - url: /static/(.*)
    static_files: static/\1
    upload: static/(.*)

  - url: /
    script: index.php

  - url: /(.+)
    script: index.php